# Generated by Django 5.0.4 on 2024-04-24 11:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], default='action', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_card',
            field=models.ImageField(default='default_image.jpg', upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie_videos/'),
        ),
    ]
